#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

export xVERSION=0.42
APPLICATION="SSD"
CODENAME="Heavywheight Jam"

ERR_MSG=""

PREFIX="/usr"
BINDIR="$PREFIX/bin"
DATADIR="$PREFIX/share/"

MODE=user
QUIET=false

export OLDPATH=$PATH
export PATH="$PATH:/sbin:/usr/sbin:/usr/local/sbin"
