#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

IN_FILES=( wrapper Makefile )

copy_in_files () {

	for in_file in ${IN_FILES[@]}; do
		cp "${in_file}".in "${in_file}";
	done

}

substitute_values () {

	# substitute PREFIX
	sed -e "s>@PREFIX@>$PREFIX>g" -i ${IN_FILES[@]}
	sed -e "s>//>/>g" -i ${IN_FILES[@]}

}
